apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-web-hello-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sagnofelix/argocd.git
    targetRevision: HEAD
    path: ./
  destination: 
    server: https://kubernetes.default.svc
    namespace: k8s-web-hello-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true