apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app-deployment
spec:
  selector:
    matchLabels:
      app: argocd-app
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
      - name: argocd-app
        image: jeanfelixsagno/k8s-web-hello:1.0.0
        ports:
        - containerPort: 8080
